# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

2. Create a null vector of size 10 

In [7]:
null_vector = np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [11]:
values_vector = np.arange(10, 50)
values_vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [12]:
values_vector.shape

(40,)

5. Print the type of the previous array in question 3

In [13]:
type(values_vector)

numpy.ndarray

6. Print the numpy version and the configuration


In [15]:
np.__version__

'1.19.3'

7. Print the dimension of the array in question 3


In [17]:
values_vector.ndim

1

8. Create a boolean array with all the True values

In [19]:
bool_array = values_vector>=0
bool_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [22]:
two_dim_array = np.arange(0, 10).reshape(2,5)
two_dim_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [23]:
three_dim_array = np.arange(0, 27).reshape(3,3,3)
three_dim_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [30]:
vec = np.arange(0,10)
# vec = vec[::-1]
rev_vec = np.flip(vec)
rev_vec

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [33]:
n_vec = np.zeros(10)
n_vec[4] = 1
n_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [36]:
identity_matrix = np.identity(3, dtype=np.int)
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [42]:
arr = np.array([1, 2, 3, 4, 5]).astype(np.float)
arr.dtype

dtype('float64')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [44]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print("Array 1:\n{}\nArray2:\n{}".format(arr1, arr2))
prod = arr1 * arr2
print("Product: {}".format(prod))

Array 1:
[[1. 2. 3.]
 [4. 5. 6.]]
Array2:
[[ 0.  4.  1.]
 [ 7.  2. 12.]]
Product: [[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [46]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])                    
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr3 = np.where(arr1>arr2, arr1, arr2)
print(arr3)

[[ 1.  4.  3.]
 [ 7.  5. 12.]]


17. Extract all odd numbers from arr with values(0-9)

In [49]:
arr = np.arange(0,10)
# odd_array = arr[arr%2!=0]
# another way
odd_array = arr[1::2]
odd_array

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [52]:
print("Original Array: {}".format(arr))
arr[odd_array] = -1
print("Changed Array: {}".format(arr))

Original Array: 
Changed Array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [55]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [58]:
sq_shape_array = np.ones((5,5))
sq_shape_array[1:-1,1:-1] = 0
sq_shape_array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [59]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [62]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [71]:
array2d = np.arange(0,10).reshape(2,5)
print("2d array {}".format(array2d))
sliced_array = array2d[0]
print("Sliced Array: {}".format(sliced_array))

2d array [[0 1 2 3 4]
 [5 6 7 8 9]]
1
Sliced Array: [0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [73]:
arr2d = np.arange(0,10).reshape(2,5)
print("original array: {}".format(arr2d))
print("2nd value means 1st index: {}".format(arr2d[1:,1:2]))

original array: [[0 1 2 3 4]
 [5 6 7 8 9]]
2nd value means 1st index: [[6]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [80]:
arr2d = np.arange(0,12).reshape(3,4)
print("Original array: {}".format(arr2d))
print("third column of first two rows: {}".format(arr2d[:2,2:3]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
third column of first two rows: [[2]
 [6]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [83]:
ar10 = np.random.randint(0, 50, (10,10))
print("original array: {}".format(ar10))
print("Minimum value: {}".format(np.min(ar10)))
print("Maximum value: {}".format(np.max(ar10)))

original array: [[15  1 44 25 34 21 19 10  8 11]
 [45 35  9 33 33  1 19 21 42 14]
 [42 28 38  1 38  3 38 18 14  1]
 [44 39 20  2  2 26 37 40 28  0]
 [43 48 20  4 44  8  0 25 29 48]
 [43 15  9  4 25 20 27 17 25 22]
 [15 40 20 47 15 44  4 15 46  4]
 [18  3 41 21  7 34 36  3 21  3]
 [ 2  8 30 17  7 25  4 45 37  6]
 [26 15  1 46 11 12 27 44 49 12]]
Minimum value: 0
Maximum value: 49


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [86]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Common elements in\n{}\nand\n{}\nare:\n{}".format(a, b, np.intersect1d(a, b)))

Common elements in
[1 2 3 2 3 4 3 4 5 6]
and
[ 7  2 10  2  7  4  9  4  9  8]
are:
[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [88]:
print(np.argwhere(a==b))

[[1]
 [3]
 [5]
 [7]]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [91]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data[names!="Will"])

[[-1.19018203  1.02515516 -1.05296913 -1.94031081]
 [ 0.07018292 -0.52728423  0.6284544  -1.07622514]
 [ 0.98918763 -2.41287318 -2.39896168 -0.35195574]
 [ 1.31716124 -1.40804449  0.40539291 -0.36090025]
 [-0.76102935  1.50980201 -1.08969087  0.51101902]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data[np.logical_and(names!="Will", names!="Joe")])

[[ 0.68121785  0.39492012 -0.55353457 -0.05042311]
 [ 0.67499595 -0.87478516  0.17055668 -0.55887661]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [115]:
decimal_array = 15 * np.random.random_sample((5,3)) + 1
decimal_array

array([[ 3.22624159,  9.42032093,  4.78437362],
       [12.5870679 , 10.93845737, 14.58261026],
       [ 9.70880557,  6.91457695, 10.42019295],
       [ 9.24677876,  3.26334118, 13.9367942 ],
       [ 6.77720283,  2.91624345,  7.63989947]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [116]:
decimal_array = 16 * np.random.random_sample((2,2,4)) + 1
decimal_array

array([[[ 9.01443765,  2.40435912,  6.8416735 ,  2.22616879],
        [ 6.76527892,  4.57307269, 13.42940826, 16.22750399]],

       [[ 5.91480067, 10.8903664 ,  8.4404138 ,  1.95488151],
        [ 5.56426903, 12.24198592, 13.08095668, 15.02414008]]])

33. Swap axes of the array you created in Question 32

In [121]:
print(np.flip(decimal_array, axis=0))

[[[ 5.91480067 10.8903664   8.4404138   1.95488151]
  [ 5.56426903 12.24198592 13.08095668 15.02414008]]

 [[ 9.01443765  2.40435912  6.8416735   2.22616879]
  [ 6.76527892  4.57307269 13.42940826 16.22750399]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [130]:
a = np.linspace(0, 1, 10)
b = np.where(np.sqrt(a) < 0.5, 0, np.sqrt(a))
b

array([0.        , 0.        , 0.        , 0.57735027, 0.66666667,
       0.74535599, 0.81649658, 0.8819171 , 0.94280904, 1.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [132]:
ar1 = np.random.randint(0, 50, (2, 8))
ar2 = np.random.randint(0, 50, (2, 8))
print(ar1)
ar2

[[32 27 15 21 49 44  1  8]
 [44 28 33 39 11 44 11  8]]


array([[20, 36, 16, 39, 42, 49, 49, 45],
       [45, 11, 16,  4, 24, 21, 15, 17]])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [134]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
# Already sorted

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [142]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a, b)
a

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [157]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
np.insert(sampleArray, 1, newColumn, axis=1)
sampleArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [161]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(np.dot(x, y))

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [164]:
a = np.random.randint(1, 20, (2,5))
print(a)
print("Commulative sum: {}".format(np.cumsum(a)))

[[ 4 12 12  6  8]
 [17 16 15  7 12]]
Commulative sum: [  4  16  28  34  42  59  75  90  97 109]
