In [1]:
import numpy as np

In [13]:
arr = np.arange(16)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
16
1


In [14]:
arr = np.arange(1, 17).reshape(4,4)
print(arr)
print(arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2


In [16]:
x = (1,2,3)
y = [5,6,7]

arr1 = np.array(x)
print(arr1, type(arr1))
arr2 = np.array(y)
print(arr2, type(arr2))
arr3 = np.array((x,y))
print(arr3)

[1 2 3] <class 'numpy.ndarray'>
[5 6 7] <class 'numpy.ndarray'>
[[1 2 3]
 [5 6 7]]


In [18]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
l = [1,2,3]
a = np.asarray(l)
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [22]:
one = np.ones((4,4), dtype=np.int)
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [25]:
zero = np.zeros((4,4), dtype=np.int)
print(zero)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
ones_l = np.ones_like(zero)
print(ones_l)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [27]:
zero_l = np.zeros_like(ones_l)
print(zero_l)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [29]:
em = np.empty((8,4))
print(em)

[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  3.76231868e+174]
 [ 6.86671861e-091  8.60677318e-067  6.54528647e-043  1.60274505e-051]
 [ 3.99910963e+252  1.46030983e-319  0.00000000e+000 -1.62969520e-310]
 [ 1.08647873e-311  3.16202013e-322  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  4.05313832e+174  1.00653845e-046  1.31263129e-071]
 [ 3.14060211e-032  1.79454033e-052  1.39555610e-047  7.92565354e+165]
 [ 1.17660971e-047 -1.68401826e-310  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000 -3.96558814e-310  0.00000000e+000  0.00000000e+000]]


In [30]:
em_l = np.empty_like(ones_l)
print(em_l)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [38]:
f = np.full((3,4), 5, dtype=np.float)
print(f)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [41]:
f_l = np.full_like(f, 19, dtype=np.int)
print(f_l)

[[19 19 19 19]
 [19 19 19 19]
 [19 19 19 19]]


In [42]:
o_l = np.full_like(f, 1, dtype=np.int)
print(o_l)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [45]:
i = np.identity(8)
print(i)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [51]:
e = np.eye(3,5, 4)
print(e)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [53]:
ar1 = np.arange(1,17, dtype=np.int).reshape(4,4)
print(ar1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [54]:
ar2 = np.arange(17,17+16, dtype=np.int).reshape(4,4)
print(ar2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [55]:
print(ar1+ar2)

[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]


In [56]:
print(ar1*ar2)

[[ 17  36  57  80]
 [105 132 161 192]
 [225 260 297 336]
 [377 420 465 512]]


In [57]:
print(ar1/ar2)

[[0.05882353 0.11111111 0.15789474 0.2       ]
 [0.23809524 0.27272727 0.30434783 0.33333333]
 [0.36       0.38461538 0.40740741 0.42857143]
 [0.44827586 0.46666667 0.48387097 0.5       ]]


In [58]:
print(ar1/2)

[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]
 [6.5 7.  7.5 8. ]]


In [65]:
print(4//2)

2


In [67]:
print(ar1<ar2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [77]:
x = np.random.randint(1, 17, 16).reshape(4,4)
print(x)

[[ 8  7  1  3]
 [ 7  9 13  9]
 [ 2  9  1  3]
 [ 7  5  2 11]]


In [78]:
y = np.random.randint(1, 17, 16).reshape(4,4)
print(y)

[[ 2 15 13 10]
 [13  6  4 14]
 [ 4  3  9  1]
 [ 7 12 14  8]]


In [81]:
print(x==y)

[[False False False False]
 [False False False False]
 [False False False False]
 [ True False False False]]


In [5]:
marr = np.arange(1, 28).reshape(3,3,3)
print(marr)
print(marr.shape)
print(marr.size)
print(marr.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(3, 3, 3)
27
3


In [7]:
ma = np.arange(1, 17).reshape(2,2,2,2)  #ndarray: n-dimensionals
print(ma.shape)
print(ma.size)
print(ma.ndim)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
(2, 2, 2, 2)
16
4


# Indexing and Slicing

In [12]:
n = np.arange(1, 11)
print(n)
print(n[9])

[ 1  2  3  4  5  6  7  8  9 10]
10


In [19]:
n = np.arange(1, 17).reshape(4,4)
print(n)
print()
print(n[3][2])
print(n[3,2])
print(type(n[3,2]))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

15
15
<class 'numpy.int32'>


In [26]:
m = np.arange(1, 11)
print(m)
print()
print(m[5::2])

[ 1  2  3  4  5  6  7  8  9 10]

[ 6  8 10]


In [39]:
m = np.arange(1, 17).reshape(4,4)
print(m)
print()
print(m[1:3,2:3])
print()
print(m[:, 2:3])
print()
print(m[0:1,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 7]
 [11]]

[[ 3]
 [ 7]
 [11]
 [15]]

[[1 2 3 4]]


In [40]:
z = np.zeros((4,3), dtype=np.int)
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [41]:
z[1:3, 1:2] = 5
print(z)

[[0 0 0]
 [0 5 0]
 [0 5 0]
 [0 0 0]]


# Broadcasting

In [44]:
(z[1:3, 1:2].shape)

(2, 1)

In [46]:
a = np.array([[5], [5]])
print(a)

[[5]
 [5]]


# Fancy Indexing

In [11]:
arr = np.arange(1, 17)
print(arr)
print(arr[1:6:2])
print()
print(arr[[0,4,9, 2]])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[2 4 6]

[ 1  5 10  3]


In [16]:
arr = np.arange(1, 17).reshape(4,4)
print(arr)
print()
print(arr[[0, 2, 3],[2, 3, 1]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[ 3 12 14]


# Boolean Indexing

In [75]:
np.random.seed(123)
arr = np.random.randint(1, 17, (4,4))
print(arr)

[[15 14 15  3]
 [13  3  7  2]
 [ 4 11 12 10]
 [ 7  2  1  2]]


In [77]:
print(arr<5)

[[False False False  True]
 [False  True False  True]
 [ True False False False]
 [False  True  True  True]]


In [81]:
print(arr[arr<5])

[3 3 2 4 2 1 2]


In [86]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names[names=='Joe'])

['Joe' 'Joe' 'Joe']


In [88]:
a = np.arange(1, 9).reshape(2,4)
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [91]:
# Transpose
print(a.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [96]:
n = np.arange(1,13).reshape(2,3,2)
print(n)
print("="*20)
print(n.T)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  7]
  [ 3  9]
  [ 5 11]]

 [[ 2  8]
  [ 4 10]
  [ 6 12]]]


In [2]:
arr = np.arange(0, 16).reshape(2,2,4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [98]:
print(arr.swapaxes(1, 2))

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [101]:
x = np.empty((2,2))
print(type(x))

<class 'numpy.ndarray'>


In [3]:
x = np.arange(5)
y = np.arange(5, 10)
print(x)
print(y)

[0 1 2 3 4]
[5 6 7 8 9]


In [4]:
print(x)
print(np.sum(x))

[0 1 2 3 4]
10


In [8]:
np.add(x, y)

array([ 5,  7,  9, 11, 13])

In [16]:
x = np.arange(1, 17).reshape(4,4)
print(x)
print()
# print(x.sum(axis=1).reshape(-1,1))
print(x.sum(axis=0))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[28 32 36 40]


In [20]:
x = np.arange(1, 17).reshape(4,4)
y = np.arange(1, 17).reshape(4,4)
print(x)
print()
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [23]:
np.concatenate((x, y), axis=1)

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12],
       [13, 14, 15, 16, 13, 14, 15, 16]])