In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.3'

In [3]:
%timeit [i for i in range(20000000)]

1.2 s ± 24.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit np.arange(20000000)

23.2 ms ± 364 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Numpy Methods:
1.	array
2.	asarray
3.	arange
4.	empty
5.	emptylike
6.	zero
7.	zerolike
8.	ones
9.	oneslike
10.	linspace
11.	full
12.	full like
13.	eye
14.	identity
15.	astype
16.	random
17.	randn
18.	randint
19.	sort
20.	concatenate
21.	vstack
22.	hstack
23.	columnstack
24.	rowstack
25.	split
26.	hsplit
27.	vsplit
28.	sum
29.	product
30.	min
31.	max
32.	mean
33.	std-dev
34.	variance
35.	cumsum
36.	cumprod
37.	sqrt
38.	square
39.	exp
40.	power
41.	abs
42.	fabs
43.	log
44.	ceil
45.	floor
46.	any
47.	all
48.	where
49.	cos
50.	tan
51.	sin

# Creating Arrays

In [2]:
# Creating array using array method
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
# another method of creating array from existing list or tuple
lst = [1,2,3,4,5,6,7,8,9,22,55,88,66,11,22,0,125,6465465,54545,13232,45454545,465465465465,545465]
as_arr = np.asarray(lst, order='C')
as_arr

array([           1,            2,            3,            4,
                  5,            6,            7,            8,
                  9,           22,           55,           88,
                 66,           11,           22,            0,
                125,      6465465,        54545,        13232,
           45454545, 465465465465,       545465], dtype=int64)

In [3]:
# Creating array using arange method
a_arr = np.arange(1000000) # we can also specify start, end and step
a_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [17]:
# Creating an empty array which intially contains random values
e_arr = np.empty(5) # creates an empty of array with 2 elements
e_arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
# Creating an empty array and getting shape of another array
dummy_arr = np.random.randint(0, 50, (3, 2))
print(dummy_arr)
empty_like_arr = np.empty_like(dummy_arr)
print(empty_like_arr)

[[10  4]
 [14 45]
 [38 40]]
[[520645440       715]
 [        0         0]
 [        1         0]]


In [6]:
# Creating an array with all 0's
z_arr = np.zeros(10)
z_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# Creating an array filled with zero and getting shape of array from another array
dummy_arr = np.random.randint(0,10, (2,3))
print(dummy_arr)
zero_like_array = np.zeros_like(dummy_arr)
zero_like_array

[[7 9 5]
 [7 1 1]]


array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
# Creating an array with all 1's
o_arr = np.ones(20)
o_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [14]:
# Creating an array of ones but getting shape of array from another array
print(dummy_arr)
ones_like_arr = np.ones_like(dummy_arr)
ones_like_arr

[[7 9 5]
 [7 1 1]]


array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
# Creating an array with elemnts lineraly spaced in given interval
l_arr = np.linspace(0,10, 5) # start, stop and no of linerly spaced elements
l_arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
# Creating an array filled with desired elements
f_array = np.full((3,3), 2)
f_array

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [8]:
# Creating an array that takes the shape from another array and filled with desired values
f_like_array = np.full_like(f_array, 6)
f_like_array

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

# Identity and Eye methods

In [9]:
identity_array = np.identity(5)
identity_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
eye_array = np.eye(5, k=2)
eye_array

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Data Type (dtype) of array

In [20]:
# Cheaking the data type of array
d_arr = np.arange(0, 100, 5)
print(d_arr.dtype)
d_arr

int32


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [21]:
# changing the dtype of array
d_arr = d_arr.astype(np.float64)
print(d_arr.dtype)
d_arr

float64


array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.])

# Array Attributes

In [22]:
n_arr = np.arange(0, 80, 5).reshape(2, 4, 2)
print(n_arr)
print("Dimensions or axis of our array: {}".format(n_arr.ndim))
print("Rows or columns in our array: {}".format(n_arr.shape))
print("Data type of our array: {}".format(n_arr.dtype))
print("Size of length of array: {}".format(n_arr.size))
print("Size of individual element in bytes: {}".format(n_arr.itemsize))
print("the buffer containing the actual elements of the array: {}".format(n_arr.data))

[[[ 0  5]
  [10 15]
  [20 25]
  [30 35]]

 [[40 45]
  [50 55]
  [60 65]
  [70 75]]]
Dimensions or axis of our array: 3
Rows or columns in our array: (2, 4, 2)
Data type of our array: int32
Size of length of array: 16
Size of individual element in bytes: 4
the buffer containing the actual elements of the array: <memory at 0x000002CB5A1AA040>


# Creating array with random numbers

In [45]:
r_arr = np.random.random((2, 2))
r_arr

array([[0.95266268, 0.01989741],
       [0.94913543, 0.87260016]])

In [49]:
r_arr = np.random.randn(3)
r_arr

array([-0.25608468,  0.33608899,  0.99094242])

In [57]:
mult_arr = np.random.randint(0, 100, size=(2, 3, 5, 2 , 2))
print(mult_arr)

[[[[[45  1]
    [80 54]]

   [[56 47]
    [63  4]]

   [[66 27]
    [66 15]]

   [[28 76]
    [63 69]]

   [[55 82]
    [47 37]]]


  [[[91 45]
    [42 10]]

   [[11 67]
    [74 93]]

   [[20  0]
    [27 95]]

   [[29 59]
    [91 97]]

   [[19 64]
    [63 18]]]


  [[[ 8 15]
    [73  4]]

   [[24 80]
    [92 36]]

   [[29 96]
    [31 25]]

   [[32 29]
    [85 97]]

   [[48 27]
    [82 51]]]]



 [[[[54 45]
    [97  7]]

   [[55 37]
    [ 6 22]]

   [[28 93]
    [ 3 75]]

   [[17 76]
    [42 69]]

   [[68 81]
    [77 80]]]


  [[[ 5 16]
    [32 51]]

   [[95  3]
    [13  1]]

   [[20 34]
    [16  6]]

   [[ 4 82]
    [19 70]]

   [[86 34]
    [91 80]]]


  [[[52  7]
    [61 55]]

   [[28  2]
    [31 90]]

   [[ 4 67]
    [80 13]]

   [[82 97]
    [10 88]]

   [[ 2 98]
    [51 17]]]]]


In [58]:
i_arr = np.random.randint(1, 20,(2, 8), dtype="int64")
i_arr

array([[10, 15, 17, 16, 15, 13,  1,  6],
       [ 5,  1,  5, 12,  2, 16, 10,  7]], dtype=int64)

# Sorting, Concatenating arrays and Spliting Arrays

In [59]:
i_arr.sort()
i_arr

array([[ 1,  6, 10, 13, 15, 15, 16, 17],
       [ 1,  2,  5,  5,  7, 10, 12, 16]], dtype=int64)

In [71]:
second_arr = rng.integers(1,20, size=(2,8))
print(second_arr)
np.concatenate((i_arr, second_arr), axis=1)

[[15  8  7 17  6  5 14 12]
 [ 1  2  8 16  8 15  7  5]]


array([[ 1,  6, 10, 13, 15, 15, 16, 17, 15,  8,  7, 17,  6,  5, 14, 12],
       [ 1,  2,  5,  5,  7, 10, 12, 16,  1,  2,  8, 16,  8, 15,  7,  5]],
      dtype=int64)

In [80]:
first_array = np.random.randint(1, 10, (3,3))
second_array = np.random.randint(11, 20, (3,3))
print("First Array:\n{}\n\nSecond Array:\n{}".format(first_array, second_array))
# using vstack and hstack
h_stack = np.hstack((first_array, second_array))
v_stack = np.vstack((first_array, second_array))
print("Concatenation using hstack: \n{}".format(h_stack))
print("Concatenation using vstack: \n{}".format(v_stack))

First Array:
[[2 8 3]
 [2 5 7]
 [8 9 4]]

Second Array:
[[16 18 19]
 [15 13 15]
 [19 19 14]]
Concatenation using hstack: 
[[ 2  8  3 16 18 19]
 [ 2  5  7 15 13 15]
 [ 8  9  4 19 19 14]]
Concatenation using vstack: 
[[ 2  8  3]
 [ 2  5  7]
 [ 8  9  4]
 [16 18 19]
 [15 13 15]
 [19 19 14]]


In [91]:
# Spliting the arrays
a_split = np.split(h_stack, [3], axis=1)
print("Split using split:\n{}".format(a_split))
h_split = np.hsplit(h_stack, [3])
print("Split using hsplit:\n{}".format(h_split))
v_split = np.vsplit(v_stack, 3)
print("Split using vsplit:\n{}".format(v_split))

Split using split:
[array([[2, 8, 3],
       [2, 5, 7],
       [8, 9, 4]]), array([[16, 18, 19],
       [15, 13, 15],
       [19, 19, 14]])]
Split using hsplit:
[array([[2, 8, 3],
       [2, 5, 7],
       [8, 9, 4]]), array([[16, 18, 19],
       [15, 13, 15],
       [19, 19, 14]])]
Split using vsplit:
[array([[2, 8, 3],
       [2, 5, 7]]), array([[ 8,  9,  4],
       [16, 18, 19]]), array([[15, 13, 15],
       [19, 19, 14]])]


In [76]:
# Similar behviour using column start and column stack
print("Concatenation using column stack:\n{}".format(np.column_stack((first_array, second_array))))
print("Concatenation using row stack:\n{}".format(np.row_stack((first_array, second_array))))

Concatenation using column stack:
[[ 1  8  1 13 13 17]
 [ 7  1  7 19 15 15]
 [ 5  3  9 15 16 17]]
Concatenation using row stack:
[[ 1  8  1]
 [ 7  1  7]
 [ 5  3  9]
 [13 13 17]
 [19 15 15]
 [15 16 17]]


   # Sum, Product, min, max, mean, std-dev, Variance, Cumsum, Cumprod

In [34]:
print("Array we are going to use: {}".format(second_arr))
# sum of all elements in an array
print("Sum: {}".format(second_arr.sum()))
# commulative sum of array
print("Cummulative Sum: {}".format(second_arr.cumsum(axis=1)))
# product of all elements in an array
print("Product: {}".format(second_arr.prod()))
# Commulative Product of array
print("Commulative Product: {}".format(second_arr.cumprod(axis=0)))
# Minimum number in an array
print("Minimum: {}".format(second_arr.min()))
# Maximum number in an array
print("Maximum: {}".format(second_arr.max()))
# Mean of the array
print("Mean: {}".format(second_arr.mean()))
# Standard Deviation of the array
print("Standard Deviation: {}".format(second_arr.std()))
# Variance of the array
print("Variance: {}".format(second_arr.var()))

Array we are going to use: [[ 8  1  1  3  1 13 10 13]
 [ 5 12 15  8  9 19 16 19]]
Sum: 153
Cummulative Sum: [[  8   9  10  13  14  27  37  50]
 [  5  17  32  40  49  68  84 103]]
Product: 15180991488000
Commulative Product: [[  8   1   1   3   1  13  10  13]
 [ 40  12  15  24   9 247 160 247]]
Minimum: 1
Maximum: 19
Mean: 9.5625
Standard Deviation: 5.957859829670382
Variance: 35.49609375


# Square, Square Root and Exponent of an array

In [15]:
number_array = np.random.randint(1, 10, (3,3))
print("Main array:\n{}".format(number_array))
print("Square array:\n{}".format(np.square(number_array)))
print("Square root array:\n{}".format(np.sqrt(number_array)))
print("2 Power array:\n{}".format(np.exp2(number_array)))
print("Power array:\n{}".format(np.power(number_array, 3)))

Main array:
[[8 6 6]
 [4 3 8]
 [8 7 1]]
Square array:
[[64 36 36]
 [16  9 64]
 [64 49  1]]
Square root array:
[[2.82842712 2.44948974 2.44948974]
 [2.         1.73205081 2.82842712]
 [2.82842712 2.64575131 1.        ]]
2 Power array:
[[256.  64.  64.]
 [ 16.   8. 256.]
 [256. 128.   2.]]
Power array:
[[512 216 216]
 [ 64  27 512]
 [512 343   1]]


# abs, fabs

In [16]:
neg_array = np.random.randint(-10, -1, (3,3))
print("Negative array\n{}".format(neg_array))
print("Absolute array\n{}".format(np.abs(neg_array)))
print("F Absolute array\n{}".format(np.fabs(neg_array)))

Negative array
[[-2 -5 -2]
 [-5 -8 -2]
 [-6 -8 -8]]
Absolute array
[[2 5 2]
 [5 8 2]
 [6 8 8]]
F Absolute array
[[2. 5. 2.]
 [5. 8. 2.]
 [6. 8. 8.]]


# log, ceil , floor

In [19]:
gen_array = np.random.ranf((3,3))
another_array = np.random.randint(10, 150, (3,3))
log_array = np.log(gen_array + another_array)
print("Log array:\n{}".format(log_array))
print("Ceil values of log array:\n{}".format(np.ceil(log_array)))
print("Floor values of log array:\n{}".format(np.floor(log_array)))

Log array:
[[3.77420461 4.45069835 2.84673879]
 [4.93566507 3.94259524 3.87003637]
 [4.92761567 4.99379052 4.83257565]]
Ceil values of log array:
[[4. 5. 3.]
 [5. 4. 4.]
 [5. 5. 5.]]
Floor values of log array:
[[3. 4. 2.]
 [4. 3. 3.]
 [4. 4. 4.]]


# any, all and where

In [27]:
numbers = np.random.randint(0, 20, (2, 10))
print("Main array:\n{}".format(numbers))
print("Any returns:{}".format(np.any(numbers>5)))
print("All returns:{}".format(np.all(numbers>5)))
print("Where returns:\n{}".format(np.where(numbers>5, "Greater", "small")))

Main array:
[[ 4 14  3 15  6  5 15 14 18 11]
 [ 1  0  0 13  4 13  5 17 11 16]]
Any returns:True
All returns:False
Where returns:
[['small' 'Greater' 'small' 'Greater' 'Greater' 'small' 'Greater'
  'Greater' 'Greater' 'Greater']
 ['small' 'small' 'small' 'Greater' 'small' 'Greater' 'small' 'Greater'
  'Greater' 'Greater']]


# sin, cos and tan

In [30]:
theta_array  = np.array([0, 90, 180, 270, 360])
print("theta values: {}".format(theta_array))
print("Sin values: {}".format(np.rint(np.sin(theta_array))))
print("Cos values: {}".format(np.rint(np.cos(theta_array))))
print("tan values: {}".format(np.rint(np.tan(theta_array))))

theta values: [  0  90 180 270 360]
Sin values: [ 0.  1. -1. -0.  1.]
Cos values: [ 1. -0. -1.  1. -0.]
tan values: [ 0. -2.  1. -0. -3.]
