list = [1,2 "a"]  
array:  continous memory blocks for homogenous data  

In [1]:
import numpy as np

In [3]:
%timeit [i for i in range(200000)]

58.3 ms ± 5.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
%timeit np.arange(200000)

327 µs ± 15.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
a = np.array([1,2,3,4], dtype=np.float)
print(a)
print(type(a))

print(a.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float64


In [13]:
b = np.array([2,3,4,5,6,"a"])
print(b)

['2' '3' '4' '5' '6' 'a']


In [18]:
c = np.array([6,7,8,1.0])
print(c)

[6. 7. 8. 1.]


In [20]:
print(a)
print(c)

print(a+c)
print(a*c)

[1. 2. 3. 4.]
[6. 7. 8. 1.]
[ 7.  9. 11.  5.]
[ 6. 14. 24.  4.]


In [23]:
print(a.dtype)
print(a)
print(a.shape)

float64
[1. 2. 3. 4.]
(4,)


In [24]:
x = np.array([[1,2], [3,4]])
print(x)
print(x.shape)

[[1 2]
 [3 4]]
(2, 2)


In [30]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


# write 50 methods/attributes of numpy