In [1]:
import numpy as np

In [13]:
arr = np.arange(16)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
16
1


In [14]:
arr = np.arange(1, 17).reshape(4,4)
print(arr)
print(arr.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2


In [16]:
x = (1,2,3)
y = [5,6,7]

arr1 = np.array(x)
print(arr1, type(arr1))
arr2 = np.array(y)
print(arr2, type(arr2))
arr3 = np.array((x,y))
print(arr3)

[1 2 3] <class 'numpy.ndarray'>
[5 6 7] <class 'numpy.ndarray'>
[[1 2 3]
 [5 6 7]]


In [18]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
l = [1,2,3]
a = np.asarray(l)
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


In [22]:
one = np.ones((4,4), dtype=np.int)
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [25]:
zero = np.zeros((4,4), dtype=np.int)
print(zero)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
ones_l = np.ones_like(zero)
print(ones_l)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [27]:
zero_l = np.zeros_like(ones_l)
print(zero_l)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [29]:
em = np.empty((8,4))
print(em)

[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  3.76231868e+174]
 [ 6.86671861e-091  8.60677318e-067  6.54528647e-043  1.60274505e-051]
 [ 3.99910963e+252  1.46030983e-319  0.00000000e+000 -1.62969520e-310]
 [ 1.08647873e-311  3.16202013e-322  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  4.05313832e+174  1.00653845e-046  1.31263129e-071]
 [ 3.14060211e-032  1.79454033e-052  1.39555610e-047  7.92565354e+165]
 [ 1.17660971e-047 -1.68401826e-310  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000 -3.96558814e-310  0.00000000e+000  0.00000000e+000]]


In [30]:
em_l = np.empty_like(ones_l)
print(em_l)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [38]:
f = np.full((3,4), 5, dtype=np.float)
print(f)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [41]:
f_l = np.full_like(f, 19, dtype=np.int)
print(f_l)

[[19 19 19 19]
 [19 19 19 19]
 [19 19 19 19]]


In [42]:
o_l = np.full_like(f, 1, dtype=np.int)
print(o_l)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [45]:
i = np.identity(8)
print(i)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [51]:
e = np.eye(3,5, 4)
print(e)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [53]:
ar1 = np.arange(1,17, dtype=np.int).reshape(4,4)
print(ar1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [54]:
ar2 = np.arange(17,17+16, dtype=np.int).reshape(4,4)
print(ar2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [55]:
print(ar1+ar2)

[[18 20 22 24]
 [26 28 30 32]
 [34 36 38 40]
 [42 44 46 48]]


In [56]:
print(ar1*ar2)

[[ 17  36  57  80]
 [105 132 161 192]
 [225 260 297 336]
 [377 420 465 512]]


In [57]:
print(ar1/ar2)

[[0.05882353 0.11111111 0.15789474 0.2       ]
 [0.23809524 0.27272727 0.30434783 0.33333333]
 [0.36       0.38461538 0.40740741 0.42857143]
 [0.44827586 0.46666667 0.48387097 0.5       ]]


In [58]:
print(ar1/2)

[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]
 [6.5 7.  7.5 8. ]]


In [65]:
print(4//2)

2


In [67]:
print(ar1<ar2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [77]:
x = np.random.randint(1, 17, 16).reshape(4,4)
print(x)

[[ 8  7  1  3]
 [ 7  9 13  9]
 [ 2  9  1  3]
 [ 7  5  2 11]]


In [78]:
y = np.random.randint(1, 17, 16).reshape(4,4)
print(y)

[[ 2 15 13 10]
 [13  6  4 14]
 [ 4  3  9  1]
 [ 7 12 14  8]]


In [81]:
print(x==y)

[[False False False False]
 [False False False False]
 [False False False False]
 [ True False False False]]
